[package]
name = "neco-felis-typing"
version = "0.1.0"
edition = "2024"

[dependencies]
neco-felis-syn = { workspace = true }
neco-felis-resolve = { workspace = true }
neco-scope = { workspace = true }
