[package]
name = "neco-felis-compile"
version = "0.1.0"
edition = "2024"

[dependencies]
neco-felis-compile-x86_64 = { path = "../neco-felis-compile-x86_64" }
neco-tempfile = { workspace = true }

[dev-dependencies]
neco-tempfile = { workspace = true }
